<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="fr_FR" sourcelanguage="en_GB">
<context>
    <name>quickExport</name>
    <message>
        <location filename="quickexport.py" line="97"/>
        <source>Export table as CSV</source>
        <translation>Exporter la table en CSV</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="106"/>
        <source>Export table as HTML</source>
        <translation>Exporter la table en HTML</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="115"/>
        <source>Export table as PDF</source>
        <translation>Exporter la table en PDF</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="124"/>
        <source>Export table to printer</source>
        <translation>Imprimer la table attributaire</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="167"/>
        <source>Please choose the destination file path.</source>
        <translation>Veuillez choisir le fichier de destination.</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="174"/>
        <source>Quick Export Plugin</source>
        <translation>Plugin Quick Export</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="174"/>
        <source>Export has been canceled</source>
        <translation>L&apos;export a été annulé</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="224"/>
        <source>Please select a vector layer first.</source>
        <translation>Merci de sélectionner d&apos;abord une couche vectorielle dans la légende.</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="246"/>
        <source>Open file</source>
        <translation>Ouvrir le fichier</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="492"/>
        <source>The layer has been successfully exported.</source>
        <translation>Les données de la couche ont bien été exportées.</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="487"/>
        <source>An error occured during layer export.</source>
        <translation>Une erreur est survenue pendant l&apos;export de la couche.</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="389"/>
        <source>Generated by QGIS QuickExport plugin</source>
        <translation>Document généré par le plugin Quick Export de QGIS</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="392"/>
        <source>Layer</source>
        <translation>Couche</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="394"/>
        <source>Abstract</source>
        <translation>Résumé</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="396"/>
        <source>Information</source>
        <translation>Information</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="397"/>
        <source>{} lines exported</source>
        <translation>{} lignes exportées</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="234"/>
        <source>Open file ?</source>
        <translation>Ouvrir le fichier ?</translation>
    </message>
</context>
</TS>
