<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="fr_FR" sourcelanguage="en_GB">
<context>
    <name>quickExport</name>
    <message>
        <location filename="quickexport.py" line="119"/>
        <source>Export table as CSV</source>
        <translation>Exporter la table en CSV</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="128"/>
        <source>Export table as HTML</source>
        <translation>Exporter la table en HTML</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="137"/>
        <source>Export table as PDF</source>
        <translation>Exporter la table en PDF</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="146"/>
        <source>Export table to printer</source>
        <translation>Imprimer la table attributaire</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="203"/>
        <source>Please choose the destination file path.</source>
        <translation>Veuillez choisir le fichier de destination.</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="174"/>
        <source>Quick Export Plugin</source>
        <translation type="obsolete">Plugin Quick Export</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="210"/>
        <source>Export has been canceled</source>
        <translation>L&apos;export a été annulé</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="272"/>
        <source>Please select a vector layer first.</source>
        <translation>Merci de sélectionner d&apos;abord une couche vectorielle dans la légende.</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="306"/>
        <source>Open file</source>
        <translation>Ouvrir le fichier</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="595"/>
        <source>The layer has been successfully exported.</source>
        <translation>Les données de la couche ont bien été exportées.</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="590"/>
        <source>An error occured during layer export.</source>
        <translation>Une erreur est survenue pendant l&apos;export de la couche.</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="479"/>
        <source>Generated by QGIS QuickExport plugin</source>
        <translation>Document généré par le plugin Quick Export de QGIS</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="482"/>
        <source>Layer</source>
        <translation>Couche</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="484"/>
        <source>Abstract</source>
        <translation>Résumé</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="486"/>
        <source>Information</source>
        <translation>Information</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="487"/>
        <source>{} lines exported</source>
        <translation>{} lignes exportées</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="234"/>
        <source>Open file ?</source>
        <translation type="obsolete">Ouvrir le fichier ?</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="220"/>
        <source>The file cannot be deleted. </source>
        <translation>Le fichier n&apos;a pu être supprimé.</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="226"/>
        <source>Error: {}</source>
        <translation>Erreur : {}</translation>
    </message>
    <message>
        <location filename="quickexport.py" line="155"/>
        <source>Open option dialog</source>
        <translation>Ouvrir la fenêtre de configuration</translation>
    </message>
</context>
<context>
    <name>quickexport_option_form</name>
    <message>
        <location filename="quickexport_option_form.py" line="104"/>
        <source>QuickExport - Settings</source>
        <translation>QuickExport - Options</translation>
    </message>
    <message>
        <location filename="quickexport_option_form.py" line="105"/>
        <source>General settings</source>
        <translation>Options générales</translation>
    </message>
    <message>
        <location filename="quickexport_option_form.py" line="106"/>
        <source>Export hidden attributes</source>
        <translation>Exporter les champs cachés</translation>
    </message>
    <message>
        <location filename="quickexport_option_form.py" line="107"/>
        <source>CSV export</source>
        <translation>Export CSV</translation>
    </message>
    <message>
        <location filename="quickexport_option_form.py" line="108"/>
        <source>Delimiter</source>
        <translation>Délimiteur</translation>
    </message>
    <message>
        <location filename="quickexport_option_form.py" line="109"/>
        <source>comma</source>
        <translation>virgule</translation>
    </message>
    <message>
        <location filename="quickexport_option_form.py" line="110"/>
        <source>tab</source>
        <translation>tabulation</translation>
    </message>
    <message>
        <location filename="quickexport_option_form.py" line="111"/>
        <source>pipe</source>
        <translation>barre</translation>
    </message>
    <message>
        <location filename="quickexport_option_form.py" line="112"/>
        <source>semicolon</source>
        <translation>point-virgule</translation>
    </message>
</context>
</TS>
